#!/usr/bin/env python3
# =============================================================================
# emit_editor.py — layout-editor param catalogue emitter for jt8000-params
# -----------------------------------------------------------------------------
# The layout editor autocompletes control keys and fills combo option lists from
# a catalogue it loads as window.PARAMS. That catalogue was a hand-copied
# params.js, so a param added to params.yaml never appeared in the editor until
# someone refreshed it by hand. This emits it from the same model as every other
# artifact, so a regenerate is all it takes for a new param to show up in the
# editor's catalogue and autocomplete.
#
# Output shape (matches the editor's importer exactly):
#   window.PARAMS = {
#     "keys":    [ "osc1.wave", ... ],              // dotted keys, sorted
#     "labels":  { "osc1.wave": "Osc1 Wave", ... }, // key -> human name
#     "options": { "osc_wave": ["SIN","SAW",...] }  // named option sets
#   };
#
# WIRING IT IN
#   Add to tools/gen_params.py main(), beside the other emitters:
#
#       from emit_editor import emit_editor, EDITOR_PATH
#       ok &= write_if_changed(EDITOR_PATH, emit_editor(doc), args.check)
#
# STANDALONE
#   python tools/emit_editor.py            # writes gen/params.js
#   python tools/emit_editor.py --check    # non-zero exit if it would change
# =============================================================================

import json
import os
import sys

# gen/params.js — drop into the editor folder (or point the editor's Import at
# it). Kept beside the other generated artifacts.
# editor/params.js — the layout editor lives at <repo>/editor/, so the catalogue
# is written straight into it: no hand-copy, and the editor can never fall out of
# step with params.yaml. Anchored to the repo root (parent of tools/).
_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EDITOR_PATH = os.path.join(_ROOT, "editor", "params.js")


def emit_editor(doc):
    """Return the contents of gen/params.js as one LF-joined string."""
    params = doc["params"]
    option_sets = doc["option_sets"]

    # keys: every param's dotted key, sorted for stable diffs.
    keys = sorted(p["key"] for p in params)

    # labels: key -> human name. Prefer `name`; fall back to the key.
    labels = {p["key"]: p.get("name", p["key"]) for p in params}

    # options: only the sets actually referenced by a param, so the catalogue
    # doesn't carry dead option lists.
    used = sorted({p["options"] for p in params if p.get("options")})
    options = {name: list(option_sets[name]) for name in used}

    payload = {"keys": keys, "labels": labels, "options": options}

    body = json.dumps(payload, ensure_ascii=False, indent=1)

    header = (
        "/* GENERATED by tools/gen_params.py from params.yaml — DO NOT HAND-EDIT.\n"
        "   Parameter catalogue for the layout editor (window.PARAMS).\n"
        "     keys:    dotted param ids (autocomplete source)\n"
        "     labels:  key -> human name\n"
        "     options: named option-string sets (combo fills)\n"
        "   Regenerate after any params.yaml change so new params appear in the\n"
        "   editor's catalogue automatically. */\n"
    )
    return header + "window.PARAMS = " + body + ";\n"


if __name__ == "__main__":
    sys.path.insert(0, os.path.dirname(__file__))
    from gen_params import build_model

    doc = build_model()
    out = emit_editor(doc)

    check = "--check" in sys.argv
    if check:
        existing = ""
        if os.path.exists(EDITOR_PATH):
            with open(EDITOR_PATH, encoding="utf-8") as f:
                existing = f.read()
        if existing != out.replace("\n", "\r\n"):
            print(f"{EDITOR_PATH}: OUT OF DATE — rerun emit_editor.py", file=sys.stderr)
            sys.exit(1)
        print(f"{EDITOR_PATH}: up to date ({len(doc['params'])} params)")
    else:
        os.makedirs(os.path.dirname(EDITOR_PATH), exist_ok=True)
        # CRLF to match the project's generated-file convention.
        with open(EDITOR_PATH, "w", encoding="utf-8", newline="\r\n") as f:
            f.write(out)
        print(f"{EDITOR_PATH}: {len(doc['params'])} params, "
              f"{len(out.splitlines())} lines written")
