#!/usr/bin/env python3
# =============================================================================
# emit_juce.py — JUCE plugin param-table emitter for jt8000-params
# -----------------------------------------------------------------------------
# The ESP32/firmware table (ParamTable.h) is generated and "just works". The
# JUCE plugin never aligned because nothing here emitted a table for it, so its
# APVTS was hand-authored and drifted. This closes that seam the same way the
# firmware one is closed: params.yaml becomes the single source for the plugin
# too, and drift stops being possible rather than merely detected.
#
# WHY juceId == key
#   The APVTS id is PERSISTED — it appears in every saved patch and host
#   automation lane, so it must be stable forever. Rather than invent and seed
#   a separate `juce_id` in params.yaml, we use the dotted `key` (osc1.wave),
#   which is already stable, unique, and exactly what the RML skin references
#   (key="osc1.wave"). No params.yaml change is needed. The key is passed
#   through verbatim as the APVTS id; if you need JUCE-legal-only characters,
#   note that dots are valid in APVTS ids, so no sanitisation is applied.
#
#   CAVEAT: if you must load patches saved by the OLD hand-authored plugin
#   (ids like amp_a / xmod_depth), those ids differ from the keys and this
#   scheme will not find them. Treat this as a fresh, canonical id scheme.
#
# WIRING IT IN
#   Add to tools/gen_params.py main(), beside the ParamTable.h write:
#
#       from emit_juce import emit_juce, JUCE_PATH
#       ok &= write_if_changed(JUCE_PATH, emit_juce(doc), args.check)
#
#   (write_if_changed / --check mirror however the existing emitter is wired;
#    if gen_params.py writes directly, follow that same shape.)
#
# STANDALONE
#   python tools/emit_juce.py            # writes gen/JtParamTable.h
#   python tools/emit_juce.py --check    # non-zero exit if it would change
# =============================================================================

import os
import sys

# gen/JtParamTable.h — sibling of the ESP ParamTable.h.
JUCE_PATH = os.path.join("gen", "JtParamTable.h")


# --- C++ literal helpers (match gen_params.py conventions) -------------------
def cpp_str(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def cpp_float(x):
    """Float literal with an 'f' suffix — the project builds with
    -Wdouble-promotion, so bare doubles are a build error."""
    s = f"{float(x):g}"
    if "." not in s and "e" not in s and "inf" not in s and "nan" not in s:
        s += ".0"
    return s + "f"


# params.yaml type -> plugin Widget hint. Mirrors the panel/firmware split so a
# param cannot be a combo in one place and a knob in another.
def widget_of(p):
    t = p["type"]
    if t == "select":
        return "Widget::Combo"
    if t == "toggle":
        return "Widget::Toggle"
    if p.get("widget") == "envelope":
        return "Widget::Fader"
    return "Widget::Knob"


TYPE_ENUM = {"continuous": "Type::Continuous", "select": "Type::Select",
             "toggle": "Type::Toggle", "int": "Type::Int"}
SCOPE_ENUM = {"patch": "Scope::Patch", "patch_shared": "Scope::PatchShared",
              "performance": "Scope::Performance", "global": "Scope::Global"}
CURVE_ENUM = {"lin": "Curve::Lin", "log": "Curve::Log", "seg2": "Curve::Seg2"}


def emit_juce(doc):
    """Return the contents of gen/JtParamTable.h as one LF-joined string."""
    params = doc["params"]
    option_sets = doc["option_sets"]
    sections = sorted(doc["sections"], key=lambda s: s["index"])

    L = []
    a = L.append

    a("// " + "=" * 75)
    a("// JtParamTable.h — GENERATED by tools/gen_params.py.  DO NOT HAND-EDIT.")
    a("// " + "=" * 75)
    a("// APVTS parameter definitions for the JUCE plugin, generated from")
    a("// params.yaml so the plugin cannot drift from the firmware.")
    a("//")
    a("// `juceId` is PERSISTED (saved patches, host automation): it is the")
    a("// dotted key verbatim and must never be re-derived or renamed.")
    a("//")
    a("// Ranges are the firmware's own engineering ranges. The plugin stores a")
    a("// normalised value in the APVTS and converts through these, so the")
    a("// plugin and engine cannot disagree about what a given value means.")
    a("// " + "=" * 75)
    a("#pragma once")
    a("")
    a("#include <cstdint>")
    a("")
    a("namespace JtParams {")
    a("")
    a("enum class Widget : uint8_t { Knob, Fader, Combo, Toggle };")
    a("enum class Type   : uint8_t { Continuous, Select, Toggle, Int };")
    a("enum class Scope  : uint8_t { Patch, PatchShared, Performance, Global };")
    a("enum class Curve  : uint8_t { Lin, Log, Seg2 };")
    a("")
    a("// True for anything a saved patch owns, whichever way it is instanced.")
    a("inline constexpr bool isPatchScope(Scope s) {")
    a("    return s == Scope::Patch || s == Scope::PatchShared;")
    a("}")
    a("")
    a("struct Option { const char* name; };")
    a("")
    a("struct Param")
    a("{")
    a("    uint16_t      paramId;      // 14-bit v2 ParamID, matches firmware")
    a("    const char*   key;          // dotted key, params.yaml")
    a("    const char*   juceId;       // APVTS id — persisted, == key")
    a("    const char*   name;         // host-visible name")
    a("    const char*   label;        // short panel legend")
    a("    Widget        widget;")
    a("    Type          type;")
    a("    Scope         scope;")
    a("    Curve         curve;")
    a("    float         min;          // engineering range")
    a("    float         max;")
    a("    float         mid;          // seg2 breakpoint (value at norm 0.5); else 0")
    a("    float         def;          // default (eng units; Select: index)")
    a("    const char*   unit;")
    a("    bool          bipolar;")
    a("    const Option* options;      // null unless widget == Combo")
    a("    uint8_t       optionCount;")
    a("    uint8_t       section;")
    a("};")
    a("")

    # --- option sets --------------------------------------------------------
    a("// " + "-" * 75)
    a("// Option sets")
    a("// " + "-" * 75)
    used = sorted({p["options"] for p in params if p.get("options")})
    for name in used:
        ident = "kOpt_" + name
        a(f"static constexpr Option {ident}[] = {{")
        for o in option_sets[name]:
            a(f"    {{ {cpp_str(o)} }},")
        a("};")
    a("")

    # --- parameters ---------------------------------------------------------
    a("// " + "-" * 75)
    a(f"// Parameters ({len(params)})")
    a("// " + "-" * 75)
    a(f"static constexpr int kNumParams = {len(params)};")
    a("")
    a("static constexpr Param kParams[kNumParams] = {")

    for p in params:
        rng = p.get("range") or {}
        t = p["type"]
        is_sel = t == "select"
        is_tog = t == "toggle"

        if is_sel:
            lo, hi = 0.0, float(len(option_sets[p["options"]]) - 1)
        elif is_tog:
            lo, hi = 0.0, 1.0
        else:
            lo, hi = float(rng.get("min", 0.0)), float(rng.get("max", 1.0))

        opts = ("kOpt_" + p["options"]) if is_sel else "nullptr"
        n_opts = len(option_sets[p["options"]]) if is_sel else 0
        sec = p["ui"]["section"] if isinstance(p.get("ui"), dict) else (p["id"] >> 7)

        a("    { 0x%04X, %-26s %-26s %-24s %-12s %-14s %-18s %-20s %-11s %-10s %-10s %-10s %-10s %-8s %-7s %-22s %2d, %2d }," % (
            p["id"],
            cpp_str(p["key"]) + ",",
            cpp_str(p["key"]) + ",",                 # juceId == key
            cpp_str(p["name"]) + ",",
            cpp_str(p.get("label", "")) + ",",
            widget_of(p) + ",",
            TYPE_ENUM[t] + ",",
            SCOPE_ENUM[p["scope"]] + ",",            # KeyError on unknown scope, by design
            CURVE_ENUM.get(rng.get("curve", "lin"), "Curve::Lin") + ",",
            cpp_float(lo) + ",",
            cpp_float(hi) + ",",
            cpp_float(rng.get("mid", 0.0)) + ",",
            cpp_float(p.get("default", 0)) + ",",
            cpp_str(p.get("unit", "")) + ",",
            ("true," if p.get("bipolar_display") else "false,"),
            opts + ",",
            n_opts,
            sec,
        ))
    a("};")
    a("")

    # --- section names ------------------------------------------------------
    a(f"static constexpr int kNumSections = {len(sections)};")
    a("static constexpr const char* kSectionNames[kNumSections] = {")
    for s in sections:
        a(f"    {cpp_str(s['name'])},")
    a("};")
    a("")
    a("} // namespace JtParams")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    # Reuse the validated model so this emitter validates identically.
    sys.path.insert(0, os.path.dirname(__file__))
    from gen_params import build_model

    doc = build_model()
    out = emit_juce(doc)

    check = "--check" in sys.argv
    if check:
        existing = ""
        if os.path.exists(JUCE_PATH):
            with open(JUCE_PATH, encoding="utf-8") as f:
                existing = f.read()
        if existing != out.replace("\n", "\r\n"):
            print(f"{JUCE_PATH}: OUT OF DATE — rerun emit_juce.py", file=sys.stderr)
            sys.exit(1)
        print(f"{JUCE_PATH}: up to date ({len(doc['params'])} params)")
    else:
        os.makedirs(os.path.dirname(JUCE_PATH), exist_ok=True)
        # CRLF to match the project's generated-file convention.
        with open(JUCE_PATH, "w", encoding="utf-8", newline="\r\n") as f:
            f.write(out)
        print(f"{JUCE_PATH}: {len(doc['params'])} parameters written")
